Repository be15-FreePath-DevPath/be15-3rd-FreePath-DevPath-FE, pull requests merged in 2025-05, with the labels that each got.

#13 feat: 헤더바 구현
  src/App.vue
  src/assets/navToggle.png
  src/components/layout/Header.vue
  src/components/layout/LayoutDefault.vue
  src/features/main/views/MainView.vue
Labels: enhancement

#23 feat: 게시글 목록 조회 페이지 구현
  package-lock.json
  package.json
  src/assets/images/board/CalendarIcon.png
  src/features/board/components/PostItem.vue
  src/features/board/components/PostListHeaderBar.vue
  src/features/board/components/SearchBar.vue
  src/features/board/router.js
  src/features/board/views/FreeBoardListView.vue
  src/features/board/views/JobBoardListView.vue
  src/features/board/views/ProjectBoardListView.vue
  src/main.js
  src/router/index.js
Labels: enhancement

#24 Feature/common header
  src/components/layout/Header.vue
  src/components/layout/LayoutDefault.vue
  src/features/main/views/MainView.vue
Labels: bug

#35 feat: 게시글 상세조회 View 페이지 구현
  package-lock.json
  package.json
  src/assets/images/board/BigHeartStraight.png
  src/assets/images/board/BookmarkSimple.png
  src/assets/images/board/Button.png
  src/assets/images/board/HeartStraight.png
  src/assets/images/board/ProfileImage.png
  src/features/board/components/PostDescriptionBar.vue
  src/features/board/components/PostItem.vue
  src/features/board/components/PostList.vue
  src/features/board/router.js
  src/features/board/views/FreeBoardListView.vue
  src/features/board/views/JobBoardListView.vue
  src/features/board/views/PostDetailView.vue
  src/features/board/views/ProjectBoardListView.vue
  src/features/comment/components/CommentInput.vue
  src/features/comment/components/CommentItem.vue
  src/features/comment/components/CommentList.vue
  src/features/interaction/components/InteractionBar.vue
  src/main.js
Labels: enhancement

#39 feat: 게시글 상세조회 View 페이지 구현
  src/features/board/components/PostInputBar.vue
  src/features/board/components/PostRegistBar.vue
  src/features/board/router.js
  src/features/board/views/FreeBoardListView.vue
  src/features/board/views/JobBoardListView.vue
  src/features/board/views/PostDetailView.vue
  src/features/board/views/PostWriteView.vue
  src/features/board/views/ProjectBoardListView.vue
Labels: enhancement

#45 Feature/csquiz
  src/features/admin/csquiz/api.js
  src/features/admin/csquiz/router.js
  src/features/admin/router.js
  src/features/mypage/MyPageView.vue
  src/features/mypage/bookmark/api.js
  src/features/mypage/bookmark/components/BookmarkList.vue
  src/features/mypage/like/api.js
  src/features/mypage/like/components/LikeList.vue
  src/features/mypage/router.js
  src/router/index.js
Labels: enhancement

#55 feat: 게시글 목록 조회 api 연결
  src/features/board/api.js
  src/features/board/components/PostInputBar.vue
  src/features/board/components/PostItem.vue
  src/features/board/components/PostList.vue
  src/features/board/components/SearchBar.vue
  src/features/board/router.js
  src/features/board/views/FreeBoardListView.vue
  src/features/board/views/JobBoardListView.vue
  src/features/board/views/ProjectBoardListView.vue
  src/features/comment/components/CommentItem.vue
Labels: enhancement

#69 Feature/interaction
  src/features/admin/ItNews/router.js
  src/features/admin/csquiz/api.js
  src/features/admin/csquiz/router.js
  src/features/admin/router.js
  src/features/csquiz/api.js
  src/features/csquiz/views/CsQuizMainView.vue
  src/features/csquiz/views/CsQuizResultView.vue
  src/features/csquiz/views/TakeCsQuizView.vue
  src/features/mypage/bookmark/api.js
  src/features/mypage/bookmark/components/BookmarkList.vue
  src/features/mypage/components/MyPageContent.vue
  src/features/mypage/components/MyPageContentList.vue
  src/features/mypage/like/api.js
  src/features/mypage/like/components/LikeList.vue
  src/features/mypage/router.js
  src/features/mypage/views/MyPageView.vue
  src/router/index.js
Labels: enhancement

#73 feat: App.vue 렌더링 시 RefreshToken를 통한 정보 불러오기 구현
  src/features/user/api.js
  src/main.js
Labels: enhancement

#75 [Fix #74] axios interceptor refresh 경로 수정
  src/api/axios.js
  src/main.js
Labels: enhancement

#97 Feature/interaction
  src/features/mypage/components/MyPageContent.vue
  src/features/mypage/components/MyPageContentList.vue
  src/features/mypage/reportedpost/api.js
  src/features/mypage/reportedpost/components/ReportedPostList.vue
  src/features/mypage/writepost/api.js
  src/features/mypage/writepost/components/WritePostList.vue
Labels: enhancement

#101 Feature/interaction
  src/features/admin/csquiz/components/CsQuizList.vue
  src/features/mypage/bookmark/components/BookmarkList.vue
  src/features/mypage/comment/components/CommentList.vue
  src/features/mypage/comment/components/ReportCommentList.vue
  src/features/mypage/like/components/LikeList.vue
  src/features/mypage/reportedpost/components/ReportedPostList.vue
  src/features/mypage/writepost/components/WritePostList.vue
Labels: enhancement

#103 feat: 게시글 작성 기능 구현
  src/features/board/api.js
  src/features/board/components/PostDescriptionBar.vue
  src/features/board/components/PostInputBar.vue
  src/features/board/components/PostItem.vue
  src/features/board/views/PostDetailView.vue
  src/features/board/views/PostWriteView.vue
Labels: enhancement

#109 [feature #76] 좋아요, 북마크 회원 비회원 기능 수정
  src/features/comment/components/CommentItem.vue
  src/features/interaction/components/InteractionBar.vue
Labels: enhancement

#111 feat: 비로그인 상태에서 게시글 작성 시 로그인 페이지로 redirect 처리하기
  src/features/board/router.js
  src/features/user/components/UserButtonWhite.vue
  src/features/user/views/UserLoginGeneralView.vue
  src/router/index.js
Labels: enhancement

#115 feat: 프로젝트 매칭 게시글 작성 시 채팅 등록 버튼 활성화
  src/features/board/components/PostRegistBar.vue
  src/features/board/views/PostWriteView.vue
Labels: enhancement

#122 feat: 프로젝트 매칭 게시판 채팅 생성 api 연결
  src/api/axios.js
  src/features/admin/report/components/ReportList.vue
  src/features/board/views/PostWriteView.vue
  src/features/chatting/api.js
  src/features/chatting/router.js
  src/features/main/router.js
  src/features/user/views/UserLoginGeneralView.vue
  src/router/index.js
Labels: enhancement

#126 Feature/chatting
  src/features/board/components/PostDescriptionBar.vue
  src/features/board/views/PostDetailView.vue
  src/features/chatting/api.js
  src/features/chatting/views/ChattingView.vue
  src/features/comment/components/CommentItem.vue
  src/features/comment/components/CommentList.vue
Labels: enhancement

#130 chore: Quill-image-uploader 모듈 제거
  src/features/board/quill-config.js
  src/features/user/views/UserLoginGeneralView.vue
  src/main.js
Labels: bug

#143 Fix: 게시글 content <p> 태그 제거하여 렌더링
  src/features/board/components/PostDescriptionBar.vue
Labels: bug

#161 Feat: 게시글 수정 UI 업데이트 + 메인페이지에서 게시글 조회 시 헤더바 부분 내용 정상 반영
  src/features/main/components/MainContentBoard.vue
Labels: enhancement

#169 docs: 게시판 기능 - ReadMe 테스트 보고서 gif 반영
  README.md
  assets/test/board/post/게시글-검색.gif
  assets/test/board/post/게시글-삭제.gif
  assets/test/board/post/게시글-상세조회.gif
  assets/test/board/post/게시글-수정.gif
  assets/test/board/post/게시글-작성.gif
  assets/test/board/post/게시판-목록조회.gif
  assets/test/board/post/댓글-및-대댓글-작성.gif
  assets/test/board/post/댓글-삭제.gif
Labels: documentation
